// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/summary": {
            "get": {
                "description": "Gets aggregated data from Deforestation, Flood, Weather and Soil APIs. See the [API documentation](https://developer.openepi.io) for more information.\nThere is an error field for each of the APIs. If a certain API does not respond, it will instead return with an error message in the field that belong to that API.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "summary"
                ],
                "summary": "Get summary of agriculture data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Latitude",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Longitude",
                        "name": "lon",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Summary"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Deforestation": {
            "type": "object",
            "properties": {
                "daterange_tot_treeloss": {
                    "type": "number"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "models.Flood": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "intensity": {
                    "$ref": "#/definitions/models.IntensityEnum"
                },
                "issued_on": {
                    "type": "string"
                },
                "peak_day": {
                    "type": "string"
                },
                "peak_step": {
                    "type": "integer"
                },
                "peak_timing": {
                    "$ref": "#/definitions/models.PeakTimingEnum"
                }
            }
        },
        "models.IntensityEnum": {
            "type": "string",
            "enum": [
                "P",
                "R",
                "Y",
                "G"
            ],
            "x-enum-varnames": [
                "P",
                "R",
                "Y",
                "G"
            ]
        },
        "models.PeakTimingEnum": {
            "type": "string",
            "enum": [
                "BB",
                "GC",
                "GB"
            ],
            "x-enum-varnames": [
                "BB",
                "GC",
                "GB"
            ]
        },
        "models.SoilType": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "most_probable_soil_type": {
                    "description": "The most probable soil type at the queried location",
                    "type": "string"
                }
            }
        },
        "models.Summary": {
            "type": "object",
            "properties": {
                "deforestation": {
                    "description": "deforestation from 2001 to 2022 in the given coordinates.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Deforestation"
                        }
                    ]
                },
                "flood": {
                    "description": "Flood forecast in the given coordinates.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Flood"
                        }
                    ]
                },
                "soil": {
                    "description": "The most probable soil type in the given coordinates.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.SoilType"
                        }
                    ]
                },
                "weather": {
                    "description": "Current weather and rain forecast in the given coordinates.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Weather"
                        }
                    ]
                }
            }
        },
        "models.Weather": {
            "type": "object",
            "properties": {
                "air_temperature": {
                    "type": "number"
                },
                "cloud_area_fraction": {
                    "type": "number"
                },
                "error": {
                    "type": "string"
                },
                "precipitation_amount": {
                    "type": "number"
                },
                "relative_humidity": {
                    "type": "number"
                },
                "wind_from_direction": {
                    "type": "number"
                },
                "wind_speed": {
                    "type": "number"
                },
                "wind_speed_of_gust": {
                    "type": "number"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Agriculture API",
	Description:      "This API is used to get aggregated data from Deforestation, Flood, Weather and Soil APIs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
