basePath: /
definitions:
  models.Deforestation:
    properties:
      daterange_tot_treeloss:
        type: number
      error:
        type: string
    type: object
  models.Flood:
    properties:
      error:
        type: string
      intensity:
        $ref: '#/definitions/models.IntensityEnum'
      issued_on:
        type: string
      peak_day:
        type: string
      peak_step:
        type: integer
      peak_timing:
        $ref: '#/definitions/models.PeakTimingEnum'
    type: object
  models.IntensityEnum:
    enum:
    - P
    - R
    - "Y"
    - G
    type: string
    x-enum-varnames:
    - P
    - R
    - "Y"
    - G
  models.PeakTimingEnum:
    enum:
    - BB
    - GC
    - GB
    type: string
    x-enum-varnames:
    - BB
    - GC
    - GB
  models.SoilType:
    properties:
      error:
        type: string
      most_probable_soil_type:
        description: The most probable soil type at the queried location
        type: string
    type: object
  models.Summary:
    properties:
      deforestation:
        allOf:
        - $ref: '#/definitions/models.Deforestation'
        description: deforestation from 2001 to 2022 in the given coordinates.
      flood:
        allOf:
        - $ref: '#/definitions/models.Flood'
        description: Flood forecast in the given coordinates.
      soil:
        allOf:
        - $ref: '#/definitions/models.SoilType'
        description: The most probable soil type in the given coordinates.
      weather:
        allOf:
        - $ref: '#/definitions/models.Weather'
        description: Current weather and rain forecast in the given coordinates.
    type: object
  models.Weather:
    properties:
      air_temperature:
        type: number
      cloud_area_fraction:
        type: number
      error:
        type: string
      precipitation_amount:
        type: number
      relative_humidity:
        type: number
      wind_from_direction:
        type: number
      wind_speed:
        type: number
      wind_speed_of_gust:
        type: number
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact: {}
  description: This API is used to get aggregated data from Deforestation, Flood,
    Weather and Soil APIs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Agriculture API
  version: 1.0.0
paths:
  /summary:
    get:
      description: |-
        Gets aggregated data from Deforestation, Flood, Weather and Soil APIs. See the [API documentation](https://developer.openepi.io) for more information.
        There is an error field for each of the APIs. If a certain API does not respond, it will instead return with an error message in the field that belong to that API.
      parameters:
      - description: Latitude
        in: query
        name: lat
        required: true
        type: number
      - description: Longitude
        in: query
        name: lon
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Summary'
      summary: Get summary of agriculture data
      tags:
      - summary
swagger: "2.0"
